class ConceptsR {
  static const Map<String, Map<String, List<String>>> conceptsByLanguage = {
    "C": {
      "Variables & Data Types": [
        "Declaring variables",
        "Primitive data types (int, float, char)",
        "Constants (const, #define)",
        "Type conversion (implicit)",
        "Basic sizeof usage",
        "Signed vs unsigned",
        "Type casting (explicit)",
        "Enumerated types (enum)",
        "typedef for custom types",
        "Scope & lifetime of variables",
        "Storage classes (auto, static, extern, register)",
        "volatile qualifier",
        "restrict keyword (advanced optimization)",
        "Memory alignment/padding",
        "Thread-local storage",
      ],

      "Control Flow": [
        "if statement",
        "if-else ladder",
        "switch-case basics",
        "for loop",
        "while loop",
        "do-while loop",
        "Nested loops",
        "Break & continue",
        "Switch with multiple cases",
        "Using loops for patterns (triangles, tables)",
        "Loop unrolling (optimization)",
        "Recursive control flow (recursion vs loops)",
        "Conditional compilation (#if, #ifdef)",
        "Complex nested conditionals optimization",
        "State machines using switch",
      ],

      "Functions": [
        "Declaring & defining functions",
        "Function parameters (pass by value)",
        "Return types",
        "Void functions",
        "Function prototypes",
        "Recursion basics (factorial, Fibonacci)",
        "Scope of variables in functions",
        "Default return values",
        "Nested function calls",
        "Passing arrays to functions",
        "Recursion with backtracking (maze solving)",
        "Function pointers",
        "Callback mechanism",
        "Inline functions (compiler dependent)",
        "Variadic functions (stdarg.h)",
      ],

      "Arrays & Strings": [
        "Declaring arrays",
        "Accessing elements",
        "Traversing arrays",
        "Initializing arrays",
        "Declaring strings (char str[])",
        "2D arrays (matrices)",
        "Partial initialization",
        "String handling (strlen, strcpy)",
        "Passing arrays to functions",
        "Array of strings",
        "Multidimensional arrays",
        "Jagged arrays (arrays of pointers)",
        "Dynamic arrays (malloc)",
        "Custom string library implementation",
        "Wide strings (wchar_t)",
      ],

      "Pointers": [
        "Basics of pointer declaration",
        "& (address-of) operator",
        "* (dereference) operator",
        "NULL pointers",
        "Pointer to arrays",
        "Pointer arithmetic",
        "Pointers to functions",
        "Double pointers ()",
        "Pointers and strings",
        "Passing pointers to functions",
        "Dynamic memory allocation with pointers",
        "Function pointers for callbacks",
        "Pointers to structures (->)",
        "Void pointers",
        "Dangling & wild pointers",
      ],

      "Memory Management": [
        "malloc",
        "calloc",
        "free",
        "realloc",
        "sizeof operator with memory",
        "Difference between stack & heap",
        "Memory leaks",
        "Dangling pointers",
        "Garbage values & uninitialized memory",
        "Dynamic arrays with malloc",
        "Implementing custom memory allocator",
        "Memory fragmentation",
        "Double free errors",
        "Using valgrind (debugging tool)",
        "Low-level pointer arithmetic on allocated memory",
      ],

      "Structures & Unions": [
        "Declaring structures",
        "Accessing members (. operator)",
        "Initializing structures",
        "Array of structures",
        "Nested structures",
        "Pointers to structures (->)",
        "Passing structures to functions",
        "Returning structures from functions",
        "Structure within structures",
        "typedef with structures",
        "Unions and memory sharing",
        "Bit-fields in structures",
        "Self-referential structures (linked list node)",
        "Dynamic structures with malloc",
        "Structure padding & alignment",
      ],

      "File Handling": [
        "fopen and fclose",
        "File modes (r, w, a)",
        "fprintf and fscanf",
        "fgets and fputs",
        "EOF handling",
        "Binary files (fread, fwrite)",
        "File pointer positioning (fseek)",
        "ftell and rewind",
        "Error handling (perror)",
        "File append mode",
        "Random access files",
        "Locking files (system dependent)",
        "File buffering (setvbuf)",
        "Handling large files",
        "Implementing custom file I/O",
      ],

      "Preprocessors": [
        "#include usage",
        "#define macros",
        "Header files",
        "Comments and preprocessing",
        "Line continuation (\\)",
        "Function-like macros",
        "Conditional compilation (#if, #else)",
        "#undef directive",
        "Predefined macros (FILE, __LINE)",
        "Multiple includes & include guards",
        "Macro pitfalls (side effects)",
        "Creating custom header libraries",
        "Complex conditional compilation",
        "Variadic macros",
        "Using preprocessor for debugging/logging",
      ],

      "Advanced Concepts": [
        "Command line arguments (argc, argv)",
        "enum usage",
        "const qualifier",
        "Inline functions basics",
        "volatile keyword basics",
        "Error handling with errno",
        "Static functions (file scope)",
        "Register keyword optimization",
        "Function inlining & macros comparison",
        "External linkage with extern",
        "Writing a Makefile for C projects",
        "Implementing linked list",
        "Implementing stack & queue",
        "Bitwise operations for optimization",
        "Function pointers for event-driven programming",
      ],
    },
    "PYTHON": {
      "Variables & Data Types": [
        "Declaring and assigning variables",
        "Dynamic typing in Python",
        "Primitive types (int, float, bool, str)",
        "Type casting (int(), float(), str())",
        "Constants (convention and immutability)",
        "Multiple assignment",
        "Checking types (type(), isinstance())",
        "Mutable vs immutable types",
        "NoneType usage",
        "Scope and lifetime of variables",
        "Global and nonlocal keywords",
        "Duck typing concept",
        "Type hints and annotations",
        "Complex numbers",
        "Memory reference and id() function",
      ],

      "Control Flow": [
        "if statement",
        "if-elif-else ladder",
        "while loop",
        "for loop with range()",
        "break, continue, pass",
        "Nested loops",
        "Loop with else clause",
        "List comprehensions",
        "Dictionary and set comprehensions",
        "Ternary conditional expression",
        "Pattern matching (match-case in Python 3.10+)",
        "Recursive functions",
        "try-except-finally blocks",
        "Raising exceptions manually",
        "Assertion statements",
      ],

      "Functions": [
        "Defining functions with def",
        "Return statements",
        "Positional and keyword arguments",
        "Default arguments",
        "Variable-length arguments (*args, **kwargs)",
        "Lambda functions",
        "Scope rules (LEGB)",
        "Closures",
        "Recursion examples (factorial, Fibonacci)",
        "Higher-order functions (map, filter, reduce)",
        "Anonymous vs named functions",
        "Decorators",
        "Docstrings and annotations",
        "Type hinting in functions",
        "Generators and yield keyword",
      ],

      "Data Structures": [
        "Lists and list operations",
        "Tuples and immutability",
        "Sets and set operations",
        "Dictionaries (key-value pairs)",
        "Nested data structures",
        "List slicing",
        "Comprehensions (list, dict, set)",
        "Stack and queue using list/deque",
        "Working with collections module",
        "Iterators and iterables",
        "Enumerate and zip functions",
        "Unpacking operators (*, **)",
        "frozenset and immutability",
        "Array module basics",
        "Namedtuple and dataclasses",
      ],

      "Strings": [
        "String declaration and formatting",
        "String indexing and slicing",
        "String methods (upper, lower, strip, etc.)",
        "String concatenation and repetition",
        "f-strings and format() method",
        "Escape characters",
        "Raw strings",
        "String comparison and membership",
        "Splitting and joining strings",
        "String immutability",
        "String iteration",
        "Multiline strings",
        "Regex (re module)",
        "String translation and encoding",
        "Unicode and bytes conversion",
      ],

      "Modules & Packages": [
        "Importing modules",
        "from ... import syntax",
        "Creating custom modules",
        "Using built-in modules (math, random, os)",
        "Working with sys.path",
        "_name_ == '_main_' idiom",
        "Reloading modules (importlib)",
        "dir() and help() usage",
        "Using pip for installing packages",
        "Virtual environments",
        "Package structure (_init_.py)",
        "Relative imports",
        "Version management with requirements.txt",
        "Creating your own Python package",
        "Using environment variables (.env)",
      ],

      "File Handling": [
        "Opening and closing files",
        "File modes (r, w, a, x)",
        "Reading and writing files",
        "with open() as context manager",
        "Reading lines (readline, readlines)",
        "Writing multiple lines",
        "Handling file exceptions",
        "Working with CSV files",
        "Working with JSON files",
        "Pickle for object serialization",
        "Binary file reading/writing",
        "File seeking and tell()",
        "Checking file existence (os.path)",
        "Deleting and renaming files",
        "Working with pathlib module",
      ],

      "Object-Oriented Programming": [
        "Defining classes and objects",
        "Constructors (_init_)",
        "Instance and class variables",
        "Methods and self keyword",
        "Inheritance basics",
        "Method overriding",
        "Super() usage",
        "Polymorphism",
        "Encapsulation (private/protected)",
        "Class methods and static methods",
        "Properties and getters/setters",
        "Magic (dunder) methods",
        "Operator overloading",
        "Abstract classes (abc module)",
        "Multiple inheritance and MRO",
      ],

      "Exception Handling": [
        "try, except, finally blocks",
        "Catching multiple exceptions",
        "else with try-except",
        "Custom exception classes",
        "Raising exceptions with raise",
        "AssertionError and assert keyword",
        "Handling specific exceptions (KeyError, ValueError, etc.)",
        "Using traceback module",
        "Exception chaining",
        "Logging exceptions",
        "Suppressing exceptions (contextlib.suppress)",
        "Clean resource handling",
        "Exception propagation",
        "KeyboardInterrupt handling",
        "Creating reusable error handlers",
      ],

      "Advanced Topics": [
        "Iterators and generators",
        "Decorators and closures",
        "Context managers (_enter, __exit_)",
        "Asyncio (asynchronous programming)",
        "Multithreading with threading module",
        "Multiprocessing for parallelism",
        "Global Interpreter Lock (GIL)",
        "Coroutines and await/async",
        "Memory management in Python",
        "Garbage collection",
        "Descriptors and metaclasses",
        "Slots optimization in classes",
        "Profiling and performance measurement",
        "Creating custom iterables",
        "Functional programming concepts",
      ],

      "Data Science & Libraries": [
        "NumPy arrays and operations",
        "Pandas DataFrames",
        "Matplotlib for visualization",
        "Seaborn for advanced plotting",
        "Scikit-learn basics",
        "Data preprocessing and cleaning",
        "Working with CSV and Excel files",
        "Statistical operations",
        "Exploratory data analysis (EDA)",
        "Using Jupyter Notebooks",
        "Python visualization best practices",
        "Correlation and regression basics",
        "NLP with NLTK/spacy basics",
        "TensorFlow or PyTorch introduction",
        "Machine learning model training basics",
      ],

      "File & OS Operations": [
        "os and sys modules",
        "Directory operations (mkdir, listdir, remove)",
        "Environment variables",
        "Command line arguments (sys.argv)",
        "Working with shutil",
        "Pathlib for modern file handling",
        "Subprocess module",
        "Working with zip and tar files",
        "File permissions and metadata",
        "Temporary files (tempfile module)",
        "Cross-platform paths (os.path.join)",
        "Reading environment (.env) securely",
        "Working with JSON, YAML, and XML",
        "Automating file tasks",
        "Logging operations",
      ],
    },
    "JAVA": {
      "Basics & Syntax": [
        "JVM, JRE, and JDK overview",
        "Java program structure (class, main method)",
        "Printing output (System.out.println)",
        "Comments (single-line, multi-line, documentation)",
        "Identifiers and keywords",
        "Data types (primitive & non-primitive)",
        "Variables (local, instance, static)",
        "Constants (final keyword)",
        "Type casting (implicit & explicit)",
        "Operators (arithmetic, relational, logical, bitwise, assignment)",
        "Input using Scanner class",
        "Command line arguments",
        "Escape sequences",
        "Wrapper classes (Integer, Double, etc.)",
        "Autoboxing and unboxing",
      ],

      "Control Flow": [
        "if statement",
        "if-else ladder",
        "switch-case (with strings & enums)",
        "for loop",
        "while loop",
        "do-while loop",
        "break and continue",
        "Nested loops",
        "Enhanced for loop (for-each)",
        "Return statement",
        "Labelled break/continue",
        "Pattern generation using loops",
        "Recursion vs iteration",
        "Exception in loops (try-catch inside loop)",
        "Nested conditionals and switch fallthrough",
      ],

      "Functions & Methods": [
        "Defining and calling methods",
        "Return types and parameters",
        "Method overloading",
        "Static methods",
        "Varargs (... syntax)",
        "Recursion (factorial, Fibonacci)",
        "Passing objects to methods",
        "Scope of variables",
        "Access modifiers in methods",
        "Method chaining",
        "Pure and impure functions",
        "Lambda expressions (Java 8+)",
        "Functional interfaces",
        "Default and static methods in interfaces",
        "Recursive backtracking (maze problems)",
      ],

      "Object-Oriented Programming": [
        "Classes and objects",
        "Constructors and constructor overloading",
        "this keyword",
        "Static members",
        "Inheritance (extends keyword)",
        "Method overriding",
        "super keyword",
        "Polymorphism (compile-time & runtime)",
        "Abstract classes and methods",
        "Interfaces and multiple inheritance",
        "Encapsulation (getters/setters)",
        "Access modifiers (public, private, protected, default)",
        "final, static, transient, synchronized keywords",
        "Composition and Aggregation",
        "Inner and anonymous classes",
      ],

      "Arrays & Strings": [
        "Declaring arrays",
        "Initializing arrays",
        "Multidimensional arrays",
        "Array traversal",
        "Enhanced for loop with arrays",
        "String class basics",
        "StringBuffer and StringBuilder",
        "String methods (substring, equals, compareTo, etc.)",
        "Converting between String and char array",
        "String immutability concept",
        "Splitting and joining strings",
        "Formatting strings",
        "String interning",
        "Character class methods",
        "Pattern matching with regex",
      ],

      "Collections Framework": [
        "Collection hierarchy overview",
        "List interface (ArrayList, LinkedList)",
        "Set interface (HashSet, LinkedHashSet, TreeSet)",
        "Map interface (HashMap, TreeMap, LinkedHashMap)",
        "Queue and Deque (PriorityQueue, ArrayDeque)",
        "Iterator and ListIterator",
        "foreach loops and streams",
        "Comparable and Comparator interfaces",
        "HashCode and equals contracts",
        "Collections utility class",
        "Generics in collections",
        "Concurrent collections (ConcurrentHashMap)",
        "Immutable collections",
        "Streams API (filter, map, reduce)",
        "Optional class (null safety)",
      ],

      "Exception Handling": [
        "try, catch, finally blocks",
        "throw and throws keywords",
        "Checked vs unchecked exceptions",
        "Multiple catch blocks",
        "Nested try-catch",
        "Custom exception classes",
        "Exception hierarchy",
        "Stack trace analysis",
        "Assertions in Java",
        "Automatic resource management (try-with-resources)",
        "Error vs Exception",
        "Common exceptions (NullPointer, ArrayIndexOutOfBounds)",
        "Logging exceptions",
        "Re-throwing exceptions",
        "Suppressed exceptions handling",
      ],

      "File Handling & I/O": [
        "File class basics",
        "Reading and writing text files",
        "BufferedReader and BufferedWriter",
        "FileReader and FileWriter",
        "Scanner and PrintWriter",
        "InputStream and OutputStream",
        "Object serialization (ObjectOutputStream)",
        "Deserialization",
        "FileNotFoundException handling",
        "NIO package (Files, Paths)",
        "File copying and moving",
        "Directory traversal",
        "File permissions",
        "RandomAccessFile usage",
        "Working with temporary files",
      ],

      "Multithreading": [
        "Thread creation (extends Thread, implements Runnable)",
        "Thread lifecycle",
        "Thread.sleep() and join()",
        "Thread synchronization",
        "Synchronized blocks and methods",
        "Inter-thread communication (wait, notify, notifyAll)",
        "Thread priorities",
        "Deadlocks and race conditions",
        "Executor framework",
        "Callable and Future interfaces",
        "ThreadLocal variables",
        "Volatile keyword",
        "Atomic variables",
        "ForkJoin framework",
        "Parallel streams",
      ],

      "Memory Management": [
        "Stack vs Heap memory",
        "Garbage collection process",
        "finalize() method",
        "Strong, weak, soft, phantom references",
        "Memory leaks in Java",
        "Object pooling concept",
        "Profiling memory usage",
        "JVM tuning basics",
        "Reference queues",
        "ClassLoader memory handling",
        "Escape analysis",
        "Interned strings memory behavior",
        "OutOfMemoryError causes",
        "GC tuning (G1, CMS)",
        "Heap dump analysis",
      ],

      "Advanced Concepts": [
        "Java Packages and imports",
        "Static imports",
        "Annotations and reflection",
        "Generics (class and method level)",
        "Lambda expressions and streams",
        "Enum classes and switch on enums",
        "Record classes (Java 14+)",
        "Sealed classes (Java 17+)",
        "Modules (Java 9+)",
        "Functional programming features",
        "JDBC for database connectivity",
        "Networking (Socket programming)",
        "Serialization and Deserialization",
        "JAR creation and usage",
        "JavaFX / Swing GUI basics",
      ],
    },
  };

  static List<String> getSubtopics(String language, String topic) {
    return conceptsByLanguage[language]?[topic] ?? [];
  }

  static int getLevelCount(String language, String topic) {
    return conceptsByLanguage[language]?[topic]?.length ?? 0;
  }

  static String getSubtopicAtLevel(String language, String topic, int level) {
    final subtopics = conceptsByLanguage[language]?[topic];

    if (subtopics != null && level > 0 && level <= subtopics.length) {
      return subtopics[level - 1];
    }
    return 'Unknown Concept';
  }
}

//   // Get all languages
//   static List<String> getLanguages() {
//     return conceptsByLanguage.keys.toList();
//   }

//   // Get all topics of a language
//   static List<String> getTopics(String language) {
//     return conceptsByLanguage[language]?.keys.toList() ?? [];
//   }

//   // Get concepts for a specific language and topic
//   static List<String> getConcepts(String language, String topic) {
//     return conceptsByLanguage[language]?[topic] ?? [];
//   }
